version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: khanhtrinh2401
      MYSQL_PASSWORD: 123456
  spring-boot:
    build: .
    restart: always
    ports:
      - 8080:8080


