version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tkht
      MYSQL_USER: khanhtrinh2401
      MYSQL_PASSWORD: 123456
    networks:
      - my-network
    volumes:
      - mysqlvol:/var/lib/mysql
  spring-boot:
    image: khanhtrinh2401/tkht-cicd
    restart: always
    ports:
      - 80:8080
    networks:
      - my-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/tkht?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - MYSQL_USER:khanhtrinh2401
      - MYSQL_PASSWORD:123456
    depends_on:
      - mysqldb

networks:
  my-network:
    driver: bridge

volumes:
  mysqlvol:
